# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"
  config.vm.host_name = "ansible-quickstart.foo"
      config.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "site.yml"
        ansible.verbose = true
    end
end
