
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"
    config.vm.host_name = "demo.foo"
#    config.vm.network "private_network", ip: "192.168.31.37"
end
