# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"
  config.vm.host_name = "ansible-quickstart.foo"
  
  config.vm.provision "shell", inline: "sudo apt-get install python-pip -y"
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook.yml"
    ansible.verbose = true
    ansible.version = 'latest'
    ansible.install_mode = 'pip'
  end
end

Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: "echo Hello, World"
end